services:
 nekohub-core:
   image: nekohub-core
   build:
     context: .
     dockerfile: Dockerfile
   ports:
     - "8080:8080"
   environment:
     - ASPNETCORE_URLS=http://+:8080
   volumes:
     - ./Data:/app/Data
